config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations',
                                    sessions: 'users/sessions' }
  get 'top' =>'homes#top'
  root to: 'homes#top'
  get 'home/about'  =>'abouts#top'
  resources :books
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  belongs_to :user, optional: true


  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }

end

app/models/user.rb
class User < ApplicationRecord
  attachment :profile_image
    devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


validates :name, presence: true, length: { minimum:2, maximum: 20 },uniqueness: true
validates :introduction, length: { maximum: 50 }

has_many :books, dependent: :destroy

end

app/controllers/abouts_controller.rb
class AboutsController < ApplicationController
  def top
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!,except: [:top]

  before_action :configure_permitted_parameters, if: :devise_controller?


 protected

 def after_sign_in_path_for(resource)
   user_path(resource)
 end

 def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
 end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
     @book = Book.new
     @books = Book.all
     @user = current_user
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
    redirect_to book_path(@book)
    flash[:notice]='You have updated user successfully.'
    else
    @books = Book.all
    @user = current_user
    render :index
    end
  end

  def show
    @book_new = Book.new
    @book = Book.find(params[:id])
    @user = @book.user

  end

  def edit
    @book = Book.find(params[:id])
    if @book.user == current_user
     render "edit"
    else
     redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
   if @book.update(book_params)
    redirect_to book_path(@book)
  flash[:notice]='You have updated book successfully.'
   else
    render :edit
   end
  end

  def destroy
   book =Book.find(params[:id])
   book.destroy
   redirect_to books_path
   flash[:notice]='Book was successfully destroyed.'
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end

   def after_sign_up_path_for(resource)
   user_path(resource)
   end

end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_correct_user, only: [:edit, :update]

  def index
    @users = User.all
    @book = Book.new
    @user = current_user

  end

  def show

    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new

  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
  if @user.update(user_params)
    redirect_to user_path(@user)
  flash[:notice]='You have updated user successfully.'
  else
    render :edit
  end
  end


   private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end

  def current_user?(user)
    user == current_user
  end


 def ensure_correct_user
    user = User.find(params[:id])
     redirect_to user_path(current_user) unless current_user?(user)

 end
end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/abouts/top.html.erb
<main>
        <p id="notice"></p>
        <div class="container">
  <div class="row">
    <h1 class="px-3 mx-auto">Welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!</h1>
  </div>
</div>
      </main>

app/views/books/edit.html.erb
<h1>Editing Book</h1>


<% if @book.errors.any? %>
  <%= @book.errors.count %>error prohibited this obj from being saved:
  <% @book.errors.full_messages.each do |message| %>
  <%= message %>
  <% end %>
  <% end %>

  <%= form_with model:@book, url: book_path(@book), local:true do |f| %>

   <div class="field">
    <label for="book_title">Title</label>
   <%= f.text_field :title %>
   </div>

   <div class="field">
    <label for="book_body">Body</label>
   <%= f.text_area :body %>
   </div>

    <div class="actions">
   <%= f.submit 'Update Book' %>
   </div>

<% end %>

<%= link_to "Show", book_path(@book) %>
  |
<%= link_to "Back", books_path(@books) %>

app/views/books/index.html.erb
<main>
  <% if @book.errors.any? %>
  <%= @book.errors.count %>error prohibited this obj from being saved:
  <% @book.errors.full_messages.each do |message| %>
  <%= message %>
  <% end %>
  <% end %>
  <p id="notice"></p>
 <div class="container px-5 px-sm-0">
  <div class="row">
   <div class="col-md-3">
     <h2>User info</h2>
<table class="table">
  <tbody>
  <tr></tr>
  <tr>
  <th>name</th>
  <td><%= @user.name %></td>
  </tr>
  <tr>
  <th>introduction</th>
  <td><%= @user.introduction %></td>
  </tr>
</tbody></table>

<div class="row">
  <%= link_to "", edit_user_path(@user), class: 'btn btn-outline-secondary btn-block fas fa-user-cog' %>
  <!--<a class="btn btn-outline-secondary btn-block fas fa-user-cog edit_user_7903" href="/users/7903/edit"></a>-->
  <h2 class="mt-3">New book</h2>
<%= form_with model: @book, local:true do |f| %>
  <h4>Title</h4>
  <%= f.text_field :title %>
  <h4>Opinion</h4>
  <%= f.text_field :body %>
  <%= f.submit 'Create Book' %>
<% end %>
</div>
</div>
<div class="col-md-8 offset-md-1">
<h2>Books</h2>
<table class="table table-hober table-inverse">
 <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
       <% @books.each do |book| %> <tr>
      <td> <%= link_to user_path(book) do %>
        <%= attachment_image_tag book.user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "img/no_image.jpg" %><br>
        <% end %>
       </td>
      <td><%=link_to book_path(book) do%>
      <%= book.title %>
      <% end %>
      </td>
      <td><%= book.body %></td>
     </tr><% end %>
  </tbody>
</table>
 </div>
 </div>
</div>
</main>

app/views/books/show.html.erb
<main>
    <% if @book.errors.any? %>
  <%= @book.errors.count %>error prohibited this obj from being saved:
  <% @book.errors.full_messages.each do |message| %>
  <%= message %>
  <% end %>
  <% end %>
    <div id="error_explanation">
     <% if @book.errors.any? %>
     <%= @book.errors.count %>error prohibited this obj from being saved:
     <% @book.errors.full_messages.each do |message| %>
     <%= message %>
     <% end %>
     <% end %>
  </div>
 <div class="container px-5 px-sm-0">
  <div class="row">
   <div class="col-md-3">
     <h2>User info</h2>
     <div class="profile-container">
  <%= attachment_image_tag current_user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "img/no_image.jpg" %>
</div>
  <tbody></tbody>
  <tr></tr>
  <tr>
  <th>name</th>
  <th><%= @user.name %></th>
  </tr>
  <tr>
  <th>introduction</th>
  <th><%= @user.introduction %></th>
  </tr>
</tbody></table>
<div class="row">
  <%= link_to "", edit_user_path(@user), class: 'btn btn-outline-secondary btn-block fas fa-user-cog' %>
   <!--ここで()の中身をcurrent_userにしてしまうとこの画像をクリックしたものがcurrent_userでない限り、強制的にはじかれてしまう。つまりせっかくuser controllerで設定したbefore ensure_correctの設定が無効になってしまう-->
<!--その為、一度どのユーザーでもpathを通せるように引数を@userにする必要があった-->
  <h2 class="mt-3">New book</h2>
<%= form_with model: @book_new, local:true do |f| %>
  <h4>Title</h4>
  <%= f.text_field :title %>
  <h4>Opinion</h4>
  <%= f.text_field :body %>
  <%= f.submit 'Create Book' %>
<% end %>
</div>
</div>
<div class="col-md-8 offset-md-1">
<h2>Book detail</h2>
<table class="table table-hober table-inverse">
 <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
 </thead>
  <tbody>
       <tr>
      <td><%= attachment_image_tag @user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "img/no_image.jpg" %><br>
      <%= link_to user_path(@user) do %><%= @user.name %>
    <% end %>
      </td>
      <td> <%= link_to book_path(@book) do %><%= @book.title %>
    <% end %>
      </td>
      <td><%= @book.body %></td>
      <% if @book.user_id == current_user.id %>
      <td> <%= link_to "Edit", edit_book_path(@book) %></td>
      <td><%= link_to "Destroy", book_path(@book), method: :delete, "data-confirm" => "本当に消しますか" %></td>
      <% end %></tr>
  </tbody>
</table>

app/views/homes/top.html.erb
<main>
        <div class="container">
  <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
      <h1>welcome to <i class="fas fa-book"></i><strong>Bookers</strong>  !!</h1>
      <p>In  <i class="fas fa-book"></i><strong>Bookers</strong>, </p>
      <p>you can share and exchange  your opinions , inpressions , and emotions</p>
      <p> about various books!</p>
      <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
          <%= link_to "Log in", user_session_path(), class: 'btn btn-info btn-sm btn-block mb-3' %>
          <!--<a class="btn btn-info btn-sm btn-block mb-3 sign_in" href="/users/sign_in">Log in</a>-->
        </div>
        <div class="row">
          <%= link_to "Sign Up", new_user_registration_path, class: 'btn btn-info btn-sm btn-block mb-3' %>
          <!--<a class="btn btn-success btn-sm btn-block sign_up" href="/users/sign_up">Sign Up</a>-->
         </div>
      </div>
    </div>
  </div>
</div>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <title>Bookers2Ver2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

<!--    <meta name="csrf-param" content="authenticity_token">-->
<!--<meta name="csrf-token" content="xkxYjY4vhGVDcKLXwOnNCBZ935+K6jz4lctq2zMcfvmyLf6C3rG1YkjVdWmyntVNgKiQBaM6Xt5FOA1ew5LNgQ==">-->

<!--    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">-->
<!--    <link rel="stylesheet" media="all" href="/assets/application-16605eadccf37c23d1fa922dd614f45b9f2cf25723e2e4032f1975b02ea7d11f.css" data-turbolinks-track="reload">-->
<!--    <script src="/assets/application-3ac47b8571e58aab844e8d0a988f0f55d8a16c1a75953470343f79cf1bec8528.js" data-turbolinks-track="reload"></script>-->
  </head>

<body>
<header>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
      <!--<a class="navbar-brand" href="/"><span>Bookers</span></a>-->
       <span><%= link_to "Bookers", root_path, class: 'navbar-brand' %></span>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
          <% if user_signed_in? %>
           <li class="nav-item">
            <%= link_to "Home", user_path(current_user.id), class: 'fas fa-home nav-link text-light' %>
           </li>
           <li class="nav-item">
            <%= link_to "Users", users_path, class: 'fas fa-users nav-link text-light' %>
           </li>
           <li class="nav-item">
            <%= link_to "books", books_path, class: 'fas fa-book-open nav-link text-light' %>
           </li class="nav-item">
           <li class="nav-item">
            <%= link_to "logout", destroy_user_session_path, method: :delete, class: 'fas fa-sign-out-alt nav-link text-light' %>
           </li>
          <% else %>
           <li class="nav-item">
            <%= link_to "Home", root_path, class: 'fas fa-home nav-link text-light' %>
           </li>
           <li class="nav-item">
            <%= link_to "About", home_about_path, class: 'fas fa-link nav-link text-light' %>
           </li>
           <li class="nav-item">
            <%= link_to "sign up", new_user_registration_path, class: 'fas fa-user-plus nav-link text-light'  %>
           </li>
           <li class="nav-item">
            <%= link_to "login", new_user_session_path, class: 'fas fa-sign-in-alt nav-link text-light' %>
           </li>
          <% end %>
       </ul>
      </div>
    </div>
  </nav>
</header>
<main class="mb-auto">
<p id="notice"><%= notice %></p>

<%= yield %>
</main>
<footer>
  <div class="container mt-5">
  	<div class="row">
    	<div class="mx-auto">
    		<p>CopyRight Infratop.inc</p>
    	</div>
    </div>
  </div>
</footer>
</body>
</html>

app/views/users/edit.html.erb
<main>
 <% if @user.id == current_user.id %>
        <%= link_to edit_user_path(current_user.id) do %>
            <div class= " edit btn btn-outline-secondary btn-default btn-block" ><span class="glyphicon glyphicon-wrench" aria-hidden="true"></span></div>
        <% end %>
        <% end %>
 <div id="error_explanation">
     <% if @user.errors.any? %>
     <%= @user.errors.count %>error prohibited this obj from being saved:
     <% @user.errors.full_messages.each do |message| %>
     <%= message %>
     <% end %>
     <% end %>
  </div>
 <div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>User info</h2>
      <%= form_with model:@user,local:true do |f| %>
 　 <label for="inputName">Name</label><br>
 　<%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"名前"%><br>
 　<label for="inputImage">Image</label></br>
 　<%= f.attachment_field :profile_image %><br>
  　<label for="inputName">Introduction</label><br>
 　<%= f.text_area :introduction, autofocus: true, id:"inputName", placeholder:"説明"%><br>
    <div class="actions"><br>
   　<%= f.submit 'Update User' %>
    </div>
　　<% end %>
　  </div>
　 </div>
　</div>

app/views/users/index.html.erb
<main>
     <div id="error_explanation">
     <% if @book.errors.any? %>
     <%= @book.errors.count %>error prohibited this obj from being saved:
     <% @book.errors.full_messages.each do |message| %>
     <%= message %>
     <% end %>
     <% end %>
  </div>
</main>
 <div class="container px-5 px-sm-0">
  <div class="row">
   <div class="col-md-3">
     <h2>User info</h2>
  <%= attachment_image_tag current_user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "img/no_image.jpg" %>
<table class="table">
  <% @users.each do |user| %>
  <tbody>
  <tr></tr>
  <tr>
  <th>name</th>
  <th><%= user.name %></th>
  </tr>
  <tr>
  <th>introduction</th>
  <th><%= user.introduction %></th>
  </tr>
</tbody></table>
<% end %>

<div class="row">
  <%= link_to "", edit_user_path(@user), class: 'btn btn-outline-secondary btn-block fas fa-user-cog' %>
  <!--<a class="btn btn-outline-secondary btn-block fas fa-user-cog edit_user_7903" href="/users/7903/edit"></a>-->
  <h2 class="mt-3">New book</h2>
<%= form_with model: @book, local:true do |f| %>
  <h4>Title</h4>
  <%= f.text_field :title %>
  <h4>Opinion</h4>
  <%= f.text_field :body %>
  <%= f.submit 'Create Book' %>
<% end %>
</div>
</div>
<div class="col-md-8 offset-md-1">
<h2>Books</h2>
<table class="table table-hober table-inverse">
 <thead>
    <tr>
      <th></th>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
       <% @users.each do |user| %><tr>
      <td>
        <%= attachment_image_tag current_user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "img/no_image.jpg" %><br>
</td>
      <td><%= user.name %></td>

      <td><%= link_to "Show", user_path(user) %></td>
    </tr><% end %>
  </tbody>
</table>
  </div>
 </div>
</div>
</main>

app/views/users/show.html.erb
<main>
 <div class="container px-5 px-sm-0">
  <div class="row">
   <div class="col-md-3">
     <h2>User info</h2>

     <div class="profile-container">
       <%= attachment_image_tag current_user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "img/no_image.jpg" %>
</div>
  <tbody></tbody>
  <tr></tr>
  <tr>
  <th>name</th>
  <th><%= @user.name %></th>
  </tr>
  <tr>
  <th>introduction</th>
  <th><%= @user.introduction %></th>
  </tr>
</tbody></table>

<div class="row">
  <%= link_to "", edit_user_path(@user), class: 'btn btn-outline-secondary btn-block fas fa-user-cog' %>
  <!--ここで()の中身をcurrent_userにしてしまうとこの画像をクリックしたものがcurrent_userでない限り、強制的にはじかれてしまう。つまりせっかくuser controllerで設定したbefore ensure_correctの設定が無効になってしまう-->
<!--その為、一度どのユーザーでもpathを通せるように引数を@userにする必要があった-->
  <% if @user.errors.any? %>
  <%= @user.errors.count %>error prohibited this obj from being saved:
  <% @user.errors.full_messages.each do |message| %>
  <%= message %>
  <% end %>
  <% end %>
  <h2 class="mt-3">New book</h2>
<%= form_with model: @book, local:true do |f| %>
  <h4>Title</h4>
  <%= f.text_field :title %>
  <h4>Opinion</h4>
  <%= f.text_field :body %>
  <%= f.submit 'Create Book' %>
<% end %>
</div>
</div>
<div class="col-md-8 offset-md-1">
<h2>Books</h2>
<table class="table table-hober table-inverse">
 <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>
 <tbody>

    <% @books.each do |book| %><tr>
      <td> <%= link_to user_path(book.user) do %>
        <%= attachment_image_tag book.user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "img/no_image.jpg" %><br>
        <% end %>
       </td>
      <td><%= link_to book_path(book) do %>
      <%= book.title %>
      <% end %>
      </td>
      <td><%= book.body %></td>
    <% end %> </tr>
  </tbody>
</table>
</div>
</div>
</div>
</main>